//Search
const SEARCH_RESULTS = "SEARCH_RESULTS";
const SET_PLACE = "SET_PLACE";
const SET_DAILY = "SET_DAILY";
const SET_HOURLY = "SET_HOURLY";

//Modal
const SET_START_MODAL = "SET_START_MODAL";

export { SEARCH_RESULTS, SET_PLACE, SET_DAILY, SET_HOURLY, SET_START_MODAL };
